package no.ntnu.prog2007.ihostapi.model.dto

import no.ntnu.prog2007.ihostapi.model.entity.EventUser
import no.ntnu.prog2007.ihostapi.model.entity.EventUserRole
import no.ntnu.prog2007.ihostapi.model.entity.EventUserStatus

/**
 * Response DTO for event-user relationships.
 *
 * Enriches the [EventUser] entity with the Firestore document ID, which is
 * needed by clients to perform operations like accepting/declining invitations.
 *
 * The document ID is auto-generated by Firestore and not stored in the entity
 * itself, so this DTO bridges that gap for API responses.
 *
 * @property id Firestore document ID (required for accept/decline operations)
 * @property eventId Reference to the associated event
 * @property userId Firebase UID of the user
 * @property status Current RSVP status (PENDING, ACCEPTED, DECLINED, CREATOR)
 * @property role Permission level (CREATOR or ATTENDEE)
 * @property invitedAt ISO-8601 timestamp when the user was associated
 * @property respondedAt ISO-8601 timestamp of RSVP response (null if pending)
 */
data class EventUserResponse(
    val id: String,
    val eventId: String,
    val userId: String,
    val status: EventUserStatus,
    val role: EventUserRole,
    val invitedAt: String,
    val respondedAt: String?
) {
    companion object {
        /**
         * Factory method to create a response from an entity and its document ID.
         *
         * Used by services when converting repository results (which return
         * Pair<documentId, entity>) to API responses.
         *
         * @param eventUser The entity containing relationship data
         * @param documentId The Firestore document ID
         * @return Complete response DTO with all fields populated
         */
        fun from(eventUser: EventUser, documentId: String): EventUserResponse {
            return EventUserResponse(
                id = documentId,
                eventId = eventUser.eventId,
                userId = eventUser.userId,
                status = eventUser.status,
                role = eventUser.role,
                invitedAt = eventUser.invitedAt,
                respondedAt = eventUser.respondedAt
            )
        }
    }
}
